# Generated by Django 3.0.3 on 2020-02-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fees_title', models.CharField(max_length=64)),
                ('fees_surname', models.CharField(max_length=64)),
                ('fees_name', models.CharField(max_length=64)),
                ('fees_id', models.CharField(max_length=64)),
                ('fees_address', models.CharField(max_length=70)),
                ('fees_city', models.CharField(max_length=64)),
                ('fees_province', models.CharField(max_length=64)),
                ('fees_country', models.CharField(max_length=64)),
                ('fees_code', models.CharField(max_length=64)),
                ('fees_mobile1', models.CharField(max_length=64)),
                ('fees_mobile2', models.CharField(max_length=64)),
                ('fees_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='InternationalQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_qualification_complete', models.CharField(blank=True, max_length=64)),
                ('int_qualification_month', models.CharField(blank=True, max_length=64)),
                ('int_qualification_authority', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_of_kin_relationship', models.CharField(max_length=64)),
                ('next_of_kin_title', models.CharField(max_length=64)),
                ('next_of_kin_surname', models.CharField(max_length=64)),
                ('next_of_kin_name', models.CharField(max_length=64)),
                ('next_of_kin_id', models.CharField(max_length=64)),
                ('next_of_kin_address', models.CharField(max_length=70)),
                ('next_of_kin_city', models.CharField(max_length=64)),
                ('next_of_kin_province', models.CharField(max_length=64)),
                ('next_of_kin_country', models.CharField(max_length=64)),
                ('next_of_kin_code', models.CharField(max_length=64)),
                ('next_of_kin_mobile1', models.CharField(max_length=64)),
                ('next_of_kin_mobile2', models.CharField(max_length=64)),
                ('next_of_kin_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_name', models.CharField(max_length=64)),
                ('personal_surname', models.CharField(max_length=64)),
                ('personal_title', models.CharField(max_length=64)),
                ('personal_gender', models.CharField(max_length=64)),
                ('personal_population', models.CharField(max_length=64)),
                ('personal_marital', models.CharField(max_length=64)),
                ('personal_language', models.CharField(max_length=64)),
                ('personal_religion', models.CharField(max_length=64)),
                ('personal_disability', models.CharField(max_length=64)),
                ('personal_address', models.CharField(max_length=70)),
                ('personal_city', models.CharField(max_length=64)),
                ('personal_province', models.CharField(max_length=64)),
                ('personal_country', models.CharField(max_length=64)),
                ('personal_postal', models.CharField(max_length=64)),
                ('personal_mobile1', models.CharField(max_length=20)),
                ('personal_mobile2', models.CharField(max_length=20)),
                ('personal_citizenship', models.CharField(max_length=64)),
                ('personal_id', models.CharField(max_length=64)),
                ('personal_email', models.EmailField(max_length=254)),
                ('personal_date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SouthAfricanQualifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sa_qualification_school', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_city', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_write', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_exam', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc1', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc2', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc3', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc4', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc5', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc6', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc7', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_nsc8', models.CharField(blank=True, max_length=64)),
                ('sa_qualification_authority', models.CharField(blank=True, max_length=64)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='south_african_qualifications', to='applicant.Personal')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='details',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='document',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='specialneed',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='studyhistory',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='applicant',
        ),
        migrations.DeleteModel(
            name='Applicant',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='SpecialNeed',
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
        migrations.DeleteModel(
            name='StudyHistory',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='internationalqualifications',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_qualifications', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='fees',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='applicant.Personal'),
        ),
    ]
