# Generated by Django 3.0.3 on 2020-02-29 02:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicant', '0004_auto_20200228_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='internationalqualifications',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='international_qualifications', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='nextofkin',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='personal',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='southafricanqualifications',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='south_african_qualifications', to='applicant.Personal'),
        ),
    ]
