# Generated by Django 3.0.3 on 2020-02-29 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_auto_20200229_0229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fees',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='internationalqualifications',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='nextofkin',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='southafricanqualifications',
            name='applicant',
        ),
        migrations.AlterField(
            model_name='fees',
            name='fees_mobile2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='nextofkin',
            name='next_of_kin_mobile2',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='personal',
            name='personal_mobile2',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
