# Generated by Django 3.0.3 on 2020-03-01 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_auto_20200229_0241'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextofkin',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='applicant.Personal'),
        ),
    ]
