# Generated by Django 3.0.3 on 2020-03-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_nextofkin_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='internationalqualifications',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='international_qualifications', to='applicant.Personal'),
        ),
        migrations.AddField(
            model_name='southafricanqualifications',
            name='applicant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='south_african_qualifications', to='applicant.Personal'),
        ),
    ]
